AllCops:
  Exclude:
    - "vendor/**/*"
    - "Gemfile"
    - "Guardfile"
    - "slack_bot.gemspec"
  DisplayCopNames: true

##################### Style ##################################
#
Style/Documentation:
  Enabled: false

##################### Metrics ##################################

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20
