language: ruby
rvm:
- 2.0
- 2.1
- 2.2
- ruby-head
before_install: gem install bundler -v "~> 1.10"
bundler_args: "--jobs=2"
cache: bundler
before_script:
- export CODECLIMATE_REPO_TOKEN=46e09f028aadd0d0f7e8aa4d917dc6f053c0a3d9ab0f82aab41f0918acc0384a
script:
- ruby --version
- bundle exec rspec
branches:
  only:
  - master
notifications:
  slack:
    secure: T6QhA+PdJTpGYjOk6d9uwt/p02OLcfieVUuNOY2po6KUsw9erMXCCuCGn1TXrRwFfnSVbuA7L3zjECMvaeDlsUURLVaZZduYHCpn6VXFfKlqzFxWr51Pk1qyE1feZCDPNNkr6PbgtFPHNWzZ/NUMrG0Z8Lo91PAr/RDolAa44MvLGq1ZDfAunITBRvGz8DhAu1Uf3EMPOqKtkN8NdEHp8pkns0XhmcqNLXwohdqXJY9R/TQ1gGJBc1hx3wZAqYCy0Eda44VBuzCg72QPUVQ3seGOts+2rgksNjnNLedB4F7bL7YZUjsam5OXKppnWt5HyE5bqkG1xrh6RguGVULBUTLRG5rY+FFtgJqgg2Qp4Ttu49Iyzh2DYhYleY6lsh1B/hsxzIjP+ojD4OXFKnb93IWxRvLrvPZGT2Q9V7zTo04Xa4cl7Zz33aPk59mZ/9ZmOlUCBtUFmYMslghOyIBSdqJHvHgXiVtheu231MuWdK7jg2U/aGnPKVh0jah9aEqNBmSmDbW2xfYEA+WINJmIKEktpQLyj8S3ajsdvZUuFcKdvZ0SEPoYuJGfaxiCKvPydm5yJFstlIYmgDlpFJh7Jh+LJy1trAvWGPcQMXs1MrZsc+c/UFs7zfrr/Uh74IxfdkIztNT2ZANYQ6zfXN2ZCT2ax9iE63gSgcCRGnEJ/R0=
